# Generated by Django 5.0.4 on 2024-04-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cantact',
            options={'ordering': ('created_date',)},
        ),
    ]
