# Generated by Django 5.0.4 on 2024-07-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantact',
            name='subject',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
