# Generated by Django 5.0.4 on 2024-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
